version: "3"

volumes:
  #   var_mysql56:
    var_mysql57:
  #   var_mysql8:
    htdocs:
  #   htdocs_drupal:
  #   htdocs_wp:
  
services:

# # #
# Workers (not-auto-started)
# 

  shell:
    image: civisdk/shell
    build: 
      context: docker/sdk
      args:
        LOGIN_UID: ${LOGIN_UID}
        LOGIN_GID: ${LOGIN_GID}
        FROM_IMAGE: civisdk/php
    volumes:
      - ./volumes/home:/home/cividev
      - htdocs:/var/www/html
      - ./app:/home/cividev/app
      - ./conf:/home/cividev/conf
    profiles: ["util"] # disable auto-start
  
  mysql-cli: 
    image: mysql:5.7
    command: 
      - "/usr/bin/mysql"
      - "-h${MYSQL_HOST}"
      - "-u${MYSQL_USER}"
      - "-p${MYSQL_PASSWORD}"
    profiles: ["util"]

  mysql8-cli: 
    image: mysql:8
    command: 
      - "/usr/bin/mysql"
      - "-hmysql8"
      - "-u${MYSQL_USER}"
      - "-p${MYSQL_PASSWORD}"
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    profiles: ["util"]

# # #
# Services
# 
  php:
    image: civisdk/php
    build:
      context: docker/php
      args:
        PHP_VERSION: 7.3
        PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_PRE_74}
        # PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_POST_74}
    ports:
      - 8080:80
      - 9003:9003
      - 9000:9000
    volumes:
      - htdocs:/var/www/html
      - ./docker/php/php.sdk.ini:/usr/local/etc/php/conf.d/sdk.ini:ro
    environment:
      XDEBUG_CONFIG: client_host=${HOST_IP} # https://xdebug.org/docs/all_settings
    links:
      - mysql57

  make-do:
    image: civisdk/make-do-runner
    build: 
      context: docker/make-do
      args:
        LOGIN_UID: ${LOGIN_UID}
    # command: ["make", "reconfigure"]
    working_dir: /tmp/build
    volumes:
      - ./:/tmp/build
    profiles: ["util"]

# # #
# DB Servers
#
  mysql57: 
    image: mysql:5.7
    expose:
      - 3306
    volumes: 
      - var_mysql57:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  