version: "3"

volumes:
  #   var_mysql56:
    var_mysql57:
  #   var_mysql8:
    htdocs:
  #   htdocs_drupal:
  #   htdocs_wp:
  
services:

# # #
# Services
# 
  php:
    image: civisdk/php
    build:
      context: docker/php
      args:
        PHP_VERSION: 7.3
        PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_PRE_74}
        # PHP_CONFIGURE_GD_OPTS: ${GD_OPTS_POST_74}
    ports:
      - 8080:80
      - 9003:9003
      - 9000:9000
    volumes:
      - htdocs:/var/www/html
      - ./docker/php/php.sdk.ini:/usr/local/etc/php/conf.d/sdk.ini:ro
    environment:
      XDEBUG_CONFIG: client_host=${HOST_IP} # https://xdebug.org/docs/all_settings
    links:
      - mysql57

  make-do:
    image: civisdk/make-do-runner
    build: 
      context: docker/make-do
      args:
        LOGIN_UID: ${LOGIN_UID}
    # command: ["make", "reconfigure"]
    working_dir: /tmp/build
    volumes:
      - ./:/tmp/build
    profiles: ["util"]

# # #
# DB Servers
#
  mysql57: 
    image: mysql:5.7
    expose:
      - 3306
    volumes: 
      - var_mysql57:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  