
export MYSQL_HOST = {{MYSQL_HOST}}# mysql hostname
export MYSQL_ROOT_PASSWORD = {{MYSQL_ROOT_PASSWORD}}# 
export MYSQL_DATABASE = {{MYSQL_DATABASE}}# 
export MYSQL_USER = {{MYSQL_USER}}# 
export MYSQL_PASSWORD = {{MYSQL_PASSWORD}}# 
